### ISSUE TITLE
s3_url is ignored in operator v0.2.5 and v0.2.6

### ISSUE THREAD

**Issue by bo0ts** [openshift/oadp-operator#144]
We have a working oadp-operator configuration in OKD 4.5 with oadp-operator.v0.2.3 that uses a private minio instance.

We now tried to use that configuration on a fresh OKD 4.7 installation with the oadp-operator installed via OLM in version 0.2.5 and 0.2.6. The resulting backupstoragelocation is missing the s3Url config parameter and tries to connect to AWS. I've tried different combinations of cases, but nothing seems to work.

Our configuration:

```
apiVersion: v1
stringData:
  cloud: |
    [default]
    aws_access_key_id = XXXXXXXXXX
    aws_secret_access_key = XXXXXXXXXXXXXXX
kind: Secret
metadata:
  name: minio-dev-credentials
  namespace: oadp-operator
type: Opaque
---
apiVersion: konveyor.openshift.io/v1alpha1
kind: Velero
metadata:
  name: backup
spec:
  backup_storage_locations:
  - config:
      insecure_skip_tls_verify: "true"
      profile: default
      region: minio
      s3_force_path_style: "true"
      s3_url: https://10.127.XXX.XXX:9000
    credentials_secret_ref:
      name: minio-credentials
      namespace: oadp-operator
    name: default
    object_storage:
      bucket: backup-dev
      prefix: velero
    provider: aws
  default_velero_plugins:
  - aws
  - csi
  - openshift
  enable_restic: true
  olm_managed: true
  restic_resource_allocation:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 256Mi
```

Resulting BackupStorageLocation (missing s3Url).

```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: oadp-operator
  ownerReferences:
    - apiVersion: konveyor.openshift.io/v1alpha1
      kind: Velero
      name: backup
      uid: 0a8f049d-6aa2-4508-971f-55dcc915394a
spec:
  accessMode: ReadWrite
  config:
    insecureSkipTLSVerify: 'true'
    profile: default
    region: minio
  objectStorage:
    bucket: backup-dev
    prefix: velero
  provider: aws
```

operator-log:

```
time="2021-07-23T12:44:31Z" level=info msg="Validating backup storage location" backup-storage-location=default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:114"
```

velero log:

```
time="2021-07-23T12:52:08Z" level=info msg="Backup storage location is invalid, marking as unavailable" backup-storage-location=default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:117"
time="2021-07-23T12:52:08Z" level=error msg="Current backup storage locations available/unavailable/unknown: 0/1/0, Backup storage location \"default\" is unavailable: rpc error: code = Unknown desc = RequestError: send request failed\ncaused by: Get \"https://backup-dev.s3.minio.amazonaws.com/?delimiter=%2F&list-type=2&prefix=velero%2F\": dial tcp: lookup backup-dev.s3.minio.amazonaws.com on 10.125.0.10:53: no such host)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:164"
```
