### ISSUE TITLE
panic: invalid region provided: noobaa

### ISSUE THREAD

**Issue by anibal-aguila** [openshift/oadp-operator#149]
Hi @dymurray, please could you tell us here is our error?
We are deploying following the guide on: [Configure OADP with precreated Noobaa or Minio S3 Bucket](https://github.com/openshift/oadp-operator/blob/master/docs/noobaa/install_oadp_noobaa.md#configure-oadp-with-precreated-noobaa-or-minio-s3-bucket) we get  **CrashLoopBackOff**

**Pod issue**
```
pod/oadp-default-aws-registry-7b7788d4d8-dgkl2   0/1     CrashLoopBackOff   5          4m23s
```

**Pod Logs**
```
time="2021-07-26T11:41:13.97970582Z" level=info msg="debug server listening :5001"
panic: invalid region provided: noobaa

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x10b95a0, 0xc0004635c0, 0xc000436a80, 0x0)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:126 +0x2e41

```
**yaml file**
```
spec:
  backup_storage_locations:
  - config:
      insecure_skip_tls_verify: "true"
      profile: default
      region: noobaa
```

Thanks in advance,

**Comment by dymurray** [comment]
@anibal-aguila Thank you I will look into this. It appears that our registry instance expects a valid AWS region name. This is a bug. We may need to disable image backup/restore with Noobaa until we can resolve this.

**Comment by anibal-aguila** [comment]
Hi @dymurray thanks for care about it. We finally solve this error using the following config on the velero CR:

```
spec:
  olm_managed: true
  backup_storage_locations:
    - config:
        profile: default
        region: noobaa
        s_3__url: https://s3-openshift-storage.apps.lab4.ocp-cluster.lan
        s_3__force_path_style: true
        insecure_skip_tls_verify: true
      credentials_secret_ref:
        name: cloud-credential
        namespace: oadp-operator
      name: default
      object_storage:
```
think is related with https://github.com/openshift/oadp-operator/pull/121
