### ISSUE TITLE
Add support for loadAffinity

### ISSUE THREAD

**Issue by automate-this** [openshift/oadp-operator#1571]
**Is your feature request related to a problem? Please describe.**
At the moment it is not possible to white-/blacklist certain nodes for using the Data Mover. This results in e.g. the use of critical nodes, or nodes that don't even have access to the snapshot.

**Describe the solution you'd like**
Add support for "loadAffinity" spec directly in DPA, or add support for adding the corresponding ConfigMap in DPA.

**Describe alternatives you've considered**
Created the ConfigMap but can't add the "--node-agent-configmap=<ConfigMap name>" to the DaemonSet because it gets reverted by the operator.

**Additional context**
See velero documentation:
https://velero.io/docs/v1.15/data-movement-backup-node-selection/

**Comment by mateusoliveira43** [comment]
You can use this approach https://github.com/openshift/oadp-operator/blob/master/docs/developer/unsupported_server_args.md to use args not present in DPA. Does this fix your problem?

**Comment by automate-this** [comment]
Just to be sure. Should I add it like this?
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: node-agent-config
  namespace: openshift-adp
data:
  node-agent-configmap: affinity-configmap
```
Or can I add loadAffinity directly?

**Comment by mateusoliveira43** [comment]
must be the name of the flag in velero CLI. From your comment, it should be `node-agent-configmap`, like in your example

Do not forget that this will override **all** flags passed to DaemonSet, so you may want to add already present flags in your DaemonSet to the ConfigMap

**Comment by mateusoliveira43** [comment]
from the doc you pointed, this is present in Velero 1.15. Is it present in other Velero releases? These are the Velero versions OADP releases uses https://github.com/openshift/oadp-operator?tab=readme-ov-file#velero-version-relationship

**Comment by automate-this** [comment]
I use OADP 1.4.1, so this should correspond to velero 1.14. And this feature is present in 1.14 documentation
https://velero.io/docs/v1.14/data-movement-backup-node-selection/

**Comment by mateusoliveira43** [comment]
From 1.14 docs, the feature is present (but not clear to me how to use this feature :disappointed:), but not through Velero CLI. So my suggestion here https://github.com/openshift/oadp-operator/issues/1571#issuecomment-2435259964 will not work for your use case

**Comment by automate-this** [comment]
Thats weird because when I look at the resulting DaemonSet with the annotation on the DPA, it looks exactly like in the velero documentation. (Except for the quotation marks)
```
spec:
  template:
    spec:
      containers:
          args:
            - node-agent
            - server
            - '--node-agent-configmap=affinity-configmap'
```
