### ISSUE TITLE
OADP Operator installation on Azure Red Hat Openshift - Issues with Velero instance creation on azure cloud

### ISSUE THREAD

**Issue by sabarivijay88** [openshift/oadp-operator#293]
Hi Team,

We are configuring backup & restore feature for ARO Openshift cluster v4.7 using OADP operator and facing issues while creating Velero instance,

OADP Operator has been deployed but Velero instance is not coming up due to misconfiguration in Konveyor CR,

Operator details:

[root@spapnltispjmp01 ~]# oc get all -n oadp-operator
NAME READY STATUS RESTARTS AGE
pod/oadp-operator-68b4f7598c-6jtbg 1/1 Running 0 65m
pod/restic-5kkkf 1/1 Running 0 16m
pod/restic-5n2qd 1/1 Running 0 16m
pod/restic-7g5f5 1/1 Running 0 16m
pod/restic-dm5bh 1/1 Running 0 16m
pod/restic-mtdnp 1/1 Running 0 16m
pod/restic-zph55 1/1 Running 0 16m
pod/velero-55fcbbc6f9-l6khg 1/1 Running 0 16m

NAME DESIRED CURRENT READY UP-TO-DATE AVAILABLE NODE SELECTOR AGE
daemonset.apps/restic 6 6 6 6 6 16m

NAME READY UP-TO-DATE AVAILABLE AGE
deployment.apps/oadp-operator 1/1 1 1 65m
deployment.apps/velero 1/1 1 1 16m

NAME DESIRED CURRENT READY AGE
replicaset.apps/oadp-operator-68b4f7598c 1 1 1 65m
replicaset.apps/velero-55fcbbc6f9 1 1 1 16m

Services are not coming up and we are trying to configure backup location on azure cloud,

It will be really helpful if you share us the sample yaml about konveyor.openshift.io_veleros_crd.yaml with respective to azure cloud to complete the setup.

We able to get CR sample for AWS everywhere and we need assistance to configure Velero instance on azure cloud.

**Comment by shubham-pampattiwar** [comment]
Hello @sabarivijay88 Thank you for reaching out. Here is a sample CR for `azure` as a provider for `backupstoragelocation`
```
apiVersion: konveyor.openshift.io/v1alpha1
kind: Velero
metadata:
  name: example-velero
spec:
  default_velero_plugins:
    - openshift
    - azure
  backup_storage_locations:
   - name: default-azure
     provider: azure
     object_storage:
       bucket: <azure-bucket>
     config:
       resource_group: <azure-resource-group>
       storage_account: <azure-storage-account>
       storage_account_key_env_var: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
       subscription_id: <azure-subscription-id>
     credentials_secret_ref:
       name: cloud-credentials-azure
       namespace: oadp-operator    
```
Note: Please update the placeholder values appropriately. Also, `AZURE_STORAGE_ACCOUNT_ACCESS_KEY` is not a placeholder, keep the spec value as is.
