### ISSUE TITLE
S3Url and s3ForcePathStyle lost when operator creates BackupStorageLocation kind

### ISSUE THREAD

**Issue by gorantornqvist** [openshift/oadp-operator#306]
Hi,
I created this:
```
apiVersion: konveyor.openshift.io/v1alpha1
kind: Velero
metadata:
  name: something
  namespace: oadp-operator
spec:
  backup_storage_locations:
  - config:
      insecureSkipTlsVerify: "false"
      profile: default
      region: us-east-1
      s3ForcePathStyle: "true"
      s3Url: https://my-s3-box
      signatureVersion: "4"
snip
```
And the operator ended up creating this:
```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: something
  namespace: oadp-operator
spec:
  accessMode: ReadWrite
  config:
    insecureSkipTLSVerify: "false"
    profile: default
    region: us-east-1
    signatureVersion: "4"
snip
```
Seems like both s3Url and s3ForcePathStyle was "forgotten" ...any ideas why?
