### ISSUE TITLE
Bug: AWS plugin config: BSL Region not required when `s3ForcePathStyle` is `false`

### ISSUE THREAD

**Issue by kaovilai** [openshift/oadp-operator#424]
### Describe bug

When AWS plugin has `s3ForcePathStyle` and `s3Url` defined, a region does not need to be defined inside BSL.

### What happened?

This velero CR should not have error status
```yaml
apiVersion: oadp.openshift.io/v1alpha1
kind: Velero
metadata:
  name: example-velero
  namespace: openshift-adp
spec:
  backupStorageLocations:
    - backupSyncPeriod: 2m0s
      config:
        profile: default
        s3ForcePathStyle: 'true'
        s3Url: 'http://s3.openshift-storage.svc/'
      credential:
        key: cloud
        name: cloud-credentials
      default: true
      objectStorage:
        bucket: migstorage
        prefix: velero
      provider: aws
  defaultVeleroPlugins:
    - openshift
    - aws
    - csi
  enableRestic: true
  veleroFeatureFlags:
    - EnableCSI
  volumeSnapshotLocations:
    - config:
        profile: default
        region: us-east-1
      provider: aws
status:
  conditions:
    - lastTransitionTime: '2021-10-29T18:03:27Z'
      message: >-
        prefix and region for AWS backupstoragelocation object storage cannot be
        empty. It is required for backing up images
      reason: Error
      status: 'False'
      type: Reconciled

```

### OADP Version

0.4.x (Beta)

### OpenShift Version

4.8

### New issue

- [X] This issue is new
