### ISSUE TITLE
Bug: Post-restore hooks do not seem to apply to pods created by workload resources, but only to Pods

### ISSUE THREAD

**Issue by mperetzred** [openshift/oadp-operator#453]
### Describe bug
** Ignore the naming, doesn't have to do with cassandra application 
Post-restore hooks do not seem to be executed when applying them to pods created by [workload resources](https://kubernetes.io/docs/concepts/workloads/controllers/).
Example of Restore CR:
```
apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: Restore
  metadata:
    name: cassandra
    namespace: openshift-adp
  spec:
    backupName: cassandra-stateful
    excludedResources:
    - nodes
    - events
    - events.events.k8s.io
    - backups.velero.io
    - restores.velero.io
    - resticrepositories.velero.io
    hooks:
      resources:
      - includedNamespaces:
        - cassandra-stateful
        name: restore-hook-1
        postHooks:
        - init:
            initContainers:
            - command:
              - sleep
              - "120"
              image: alpine:latest
              name: restore-hook-init1
        - exec:
            command:
            - /bin/bash
            - -c
            - touch X
            container: busybox-pod
            execTimeout: 2m
            onError: Fail
            waitTimeout: 5m
    restorePVs: true
```
For this Pod definition, restore hooks seem to execute the hooks:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: cassandra-stateful
  labels:
    app: cassandra-stateful

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cassandra
  name: busybox
  namespace: cassandra-stateful
spec:
  containers:
  - name: busybox-pod
    image: busybox:latest
    command:
      - sleep
      - "3600"
```
I can see a container initialized for 120 seconds (the Pod is in init for about 120 or so), and then execute the command specified in exec block **(however, it fails - also seems like another issue in which the waitTimeout doesn't probably function as an appropriate mechanism to wait until the container is ready)**:
from Velero logs:
```
Defaulted container "velero" out of: velero, velero-plugin-for-aws (init), velero-plugin-for-csi (init), openshift-velero-plugin (init)
time="2021-11-15T10:17:47Z" level=info msg="stderr: time=\"2021-11-15T10:17:47Z\" level=error msg=\"exec failed: container_linux.go:380: starting container process caused: exec: \\\"/bin/bash\\\": stat /bin/bash: no such file or directory\"\n" hookCommand="[/bin/bash -c touch X]" hookContainer=busybox-pod hookName=restore-hook-1 hookOnError=Fail hookPhase=post hookSource=backupSpec hookTimeout="{2m0s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:172" pod=cassandra-stateful/busybox restore=openshift-adp/cassandra
time="2021-11-15T10:17:47Z" level=error msg="Error executing hook" error="command terminated with exit code 1" hookPhase=post hookSource=backupSpec hookType=exec logSource="internal/hook/wait_exec_hook_handler.go:173" pod=cassandra-stateful/busybox restore=openshift-adp/cassandra
time="2021-11-15T10:17:47Z" level=error msg="unable to successfully execute post-restore hooks" error="command terminated with exit code 1" logSource="pkg/restore/restore.go:1500" restore=openshift-adp/cassandra
```
In Restore CR, after all items are restored, it remains in InProgress for about 120 seconds or so and then changes to PartiallyFailed, which is expected giving the issue described above and by using "onError: Fail":
```
status:
  completionTimestamp: "2021-11-15T10:17:47Z"
  errors: 1
  phase: PartiallyFailed
  progress:
    itemsRestored: 32
    totalItems: 32
  startTimestamp: "2021-11-15T10:15:25Z"
  warnings: 18
```

------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Using the same pod within a deployment doesn't seem to run the restore hooks:
Deployment definition:
```
apiVersion: v1
kind: Namespace
metadata:
  name: cassandra-stateful
  labels:
    app: cassandra-stateful

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-stateful
  namespace: cassandra-stateful
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
      name: busybox
    spec:
      containers:
      - name: busybox-pod
        image: busybox:latest
        command:
          - sleep
          - "3600"
```

After all items are restored (reads in the Restore CR), the container in the init-restore hooks doesn't seem to be initiated, cause the phase goes immediately to Complete, and the exec-restore hooks is probably not executed either - as would expect the same issue as observed in the Pod and the phase should've changed to PartiallyFailed; also didn't see any file created by the command in the exec-restore hook.   

Also checked with a Statefulset (using this app: https://github.com/konveyor/velero-examples/tree/master/cassandra, and by changeing post-backup hooks to be post-restore hooks) so my conclusion is that it is not working on pods created by workload resources in general.

### What happened?

same as in Describe bug section

### OADP Version

0.4.x (Beta)

### OpenShift Version

4.9

### New issue

- [X] This issue is new
