### ISSUE TITLE
Bug: velero.credential.name does't take effect

### ISSUE THREAD

**Issue by XinRedhat** [openshift/oadp-operator#475]
### Contact Details

xjiang@redhat.com

### Describe bug

OADP version: 0.5.0

When I try to use GCP provider, the configuration as below, the credential name `cloud-credentials` does't take effect. it still tried to look for Secret `cloud-credentials-gcp`. 

```
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: dpa-sample
  namespace: openshift-adp
spec:
  backupLocations:
    - velero:
        credential:
          key: cloud
          name: cloud-credentials
        objectStorage:
          bucket: oadptest
          prefix: velero
        default: true
        provider: gcp
  configuration:
    restic:
      enable: true
    velero:
      defaultPlugins:
        - gcp
        - csi
  snapshotLocations:
    - velero:
        config:
          project: openshift-qe
          snapshotLocation: us-west1
        provider: gcp
        default: true
```

The command used to create secret as below:
`$ oc create secret generic cloud-credentials --namespace openshift-adp --from-file cloud=credentials-velero-gcp`

Error:
```
  spec:
    backupLocations:
    - velero:
        config:
          profile: default
        credential:
          key: cloud
          name: cloud-credentials
        default: true
        objectStorage:
          bucket: oadptest
          prefix: velero
        provider: gcp
    configuration:
      restic:
        enable: true
      velero:
        defaultPlugins:
        - gcp
        - csi
    snapshotLocations:
    - velero:
        config:
          profile: default
          region: us-west1
        provider: gcp
  status:
    conditions:
    - lastTransitionTime: "2021-11-25T08:09:54Z"
      message: Secret "cloud-credentials-gcp" not found
      reason: Error
      status: "False"
      type: Reconciled
```

### What happened?

A bug happened!

### OADP Version

0.4.x (Beta)

### OpenShift Version

4.9

### New issue

- [X] This issue is new
