### ISSUE TITLE
High severity Bug: Subscription of OADP 0.2.3 failed on openshift 4.6 and no oadp related resource was created in namespace

### ISSUE THREAD

**Issue by Frank51** [openshift/oadp-operator#499]
### Contact Details

yunqian.chen@dell.com

### Describe bug

Deployment of OADP 0.2.3 failed after creating subscription, on openshift 4.6. But deployment of OADP 0.2.3 success in openshift 4.7, 4.8. 
Since our product already released, we can not change it to use oadp 0.2.6. 

Here is the output of "oc describe sub" for oadp 0.2.3.
**oc describe sub -n velero-ppdm**
```
Name: oadp-operator
Namespace: velero-ppdm
Labels: operators.coreos.com/oadp-operator.velero-ppdm=
Annotations: <none>
API Version: operators.coreos.com/v1alpha1
Kind: Subscription
Metadata:
Creation Timestamp: 2021-12-06T17:36:09Z
Generation: 1
Managed Fields:
API Version: operators.coreos.com/v1alpha1
Fields Type: FieldsV1
fieldsV1:
f:spec:
f:config:
.:
f:resources:
f:status:
.:
f:catalogHealth:
f:conditions:
f:lastUpdated:
Manager: catalog
Operation: Update
Time: 2021-12-06T17:36:09Z
API Version: operators.coreos.com/v1alpha1
Fields Type: FieldsV1
fieldsV1:
f:metadata:
f:annotations:
.:
f:kubectl.kubernetes.io/last-applied-configuration:
f:spec:
.:
f:channel:
f:installPlanApproval:
f:name:
f:source:
f:sourceNamespace:
f:startingCSV:
Manager: kubectl-client-side-apply
Operation: Update
Time: 2021-12-06T17:36:09Z
API Version: operators.coreos.com/v1alpha1
Fields Type: FieldsV1
fieldsV1:
f:metadata:
f:labels:
.:
f:operators.coreos.com/oadp-operator.velero-ppdm:
Manager: olm
Operation: Update
Time: 2021-12-06T17:36:09Z
Resource Version: 65087
Self Link: /apis/operators.coreos.com/v1alpha1/namespaces/velero-ppdm/subscriptions/oadp-operator
UID: 62f1795b-24b9-499f-88dc-4e6823b685f6
Spec:
Channel: alpha
Install Plan Approval: Manual
Name: oadp-operator
Source: community-operators
Source Namespace: openshift-marketplace
Starting CSV: oadp-operator.v0.2.3
Status:
Catalog Health:
Catalog Source Ref:
API Version: operators.coreos.com/v1alpha1
Kind: CatalogSource
Name: certified-operators
Namespace: openshift-marketplace
Resource Version: 64168
UID: cfb50574-7241-42e5-986a-8d8373ac4cb0
Healthy: true
Last Updated: 2021-12-06T17:36:08Z
Catalog Source Ref:
API Version: operators.coreos.com/v1alpha1
Kind: CatalogSource
Name: community-operators
Namespace: openshift-marketplace
Resource Version: 62780
UID: a5c2dca3-3315-471c-b09e-6fc2a73fbe70
Healthy: true
Last Updated: 2021-12-06T17:36:08Z
Catalog Source Ref:
API Version: operators.coreos.com/v1alpha1
Kind: CatalogSource
Name: redhat-marketplace
Namespace: openshift-marketplace
Resource Version: 62271
UID: d39cdf14-576c-4b91-9783-f0cb0feddc20
Healthy: true
Last Updated: 2021-12-06T17:36:08Z
Catalog Source Ref:
API Version: operators.coreos.com/v1alpha1
Kind: CatalogSource
Name: redhat-operators
Namespace: openshift-marketplace
Resource Version: 64262
UID: 2cb48920-8f71-4e62-9248-2d62709946ba
Healthy: true
Last Updated: 2021-12-06T17:36:08Z
Conditions:
Last Transition Time: 2021-12-06T17:36:08Z
Message: all available catalogsources are healthy
Reason: AllCatalogSourcesHealthy
Status: False
Type: CatalogSourcesUnhealthy
Last Updated: 2021-12-06T17:36:08Z
Events: <none>
```
### What happened?

Deployment of OADP 0.2.3 failed on openshift 4.6. After sending oadp 0.2.3 subscription to namespace, no any OADP related resource was created in the namespace. No oadp pod, deployment or anything else.

![image](https://user-images.githubusercontent.com/26369715/144929028-e28c7335-4fa5-43e7-b292-ff3f4202ee08.png)

### OADP Version

0.2.x (Alpha)

### OpenShift Version

4.6

### New issue

- [X] This issue is new

**Comment by kaovilai** [comment]
Requested deployment logs.

**Comment by Frank51** [comment]
> Requested deployment logs/status/events.

There is no deployment shows up on the namespace. After sending the oadp subscription, no oadp-related resource can be found on the namespace.

**Comment by Frank51** [comment]
And this is the olm-operator log we have.
https://gist.github.com/Frank51/b651b10d58afdb7f8fdc1593478f1107

Other than that, this is the "OperatorGroup" yaml we used.
**OperatorGroup**
apiVersion: v1
items:
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"operators.coreos.com/v1alpha2","kind":"OperatorGroup","metadata":{"annotations":{},"creationTimestamp":null,"name":"oadp-operator","namespace":"velero-ppdm"},"spec":{"targetNamespaces":["velero-ppdm"]}}
    creationTimestamp: "2021-12-03T20:39:01Z"
    generation: 1
    managedFields:
    - apiVersion: operators.coreos.com/v1alpha2
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          .: {}
          f:targetNamespaces: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2021-12-03T20:39:01Z"
    - apiVersion: operators.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:lastUpdated: {}
          f:namespaces:
            .: {}
            v:"velero-ppdm": {}
      manager: olm
      operation: Update
      time: "2021-12-03T20:39:01Z"
    name: oadp-operator
    namespace: velero-ppdm
    resourceVersion: "316275368"
    selfLink: /apis/operators.coreos.com/v1/namespaces/velero-ppdm/operatorgroups/oadp-operator
    uid: afa84ee7-9cc7-4af1-8439-23d2816ea11a
  spec:
    targetNamespaces:
    - velero-ppdm
  status:
    lastUpdated: "2021-12-03T20:39:01Z"
    namespaces:
    - velero-ppdm
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by kaovilai** [comment]
Unable to reproduce on OpenShift 4.6 with provided subscription
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
 labels:
   operators.coreos.com/oadp-operator.velero-ppdm: ""
 name: oadp-operator
 namespace: velero-ppdm
spec:
 channel: alpha
 installPlanApproval: Manual
 name: oadp-operator
 source: community-operators
 sourceNamespace: openshift-marketplace
 startingCSV: oadp-operator.v0.2.3
```
Results from creating this subscription including installPlans generated is referenced in [resultingSubscription](https://gist.github.com/kaovilai/0d3534d945ecc6dee527032ba024a017#file-resultingsubscription)

**Comment by dymurray** [comment]
I was able to install on 4.6 doing the following:
1. Create operator group in namespace `velero-ppdm`:
```
[dymurray@galt f]$ cat og.yaml 
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: oadp-og
spec:
  targetNamespaces:
    - velero-ppmd
```
2. Create subscription:
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
 labels:
   operators.coreos.com/oadp-operator.velero-ppdm: ""
 name: oadp-operator
 namespace: velero-ppdm
spec:
 channel: alpha
 installPlanApproval: Manual
 name: oadp-operator
 source: community-operators
 sourceNamespace: openshift-marketplace
 startingCSV: oadp-operator.v0.2.3
```
3. Edit created installplan to set `approved: true` to manually approve the installation
4. Operator pod came up.

It is important you do the above in the correct order... if the subscription exists without the operator group you'll find that it never gets reconciled and updated. I believe this is an older bug in <4.6.

For debugging this... I found that the errors I needed to see to resolve them involved looking at the `catalog-operator` deployment in `openshift-operator-lifecycle-manager` namespace. I would please check those logs and grep for `oadp-operator` to see if you find any logs that indicate why the installation is failing.

**Comment by Frank51** [comment]
We are creating in the same order. Creating operator group first, then subscription. But install plan is never created. We will check the catalog-operator deployment log and get back.

**Comment by Frank51** [comment]
We found the install plan was not created at all.
```
# oc get sub -n velero-ppdm
NAME            PACKAGE         SOURCE                CHANNEL
oadp-operator   oadp-operator   community-operators   alpha

# oc get installplan -n velero-ppdm
No resources found in velero-ppdm namespace.
```

This is the catalog-operator log in oadp-operator 0.2.3.
https://gist.github.com/Frank51/0ae7360089116c78cc16829cdb513296

And this is the catalog-operator log for oadp-operator 0.2.6 case. The 0.2.6 works fine.
https://gist.github.com/Frank51/2f0210a0caf1fa5c06ef3d450a6c77c3

Here is the detailed openshift version we used.
```
# oc version
Client Version: 4.6.18
Server Version: 4.6.18
```

**Comment by anik120** [comment]
@Frank51 from the catalog operator pod logs: 
```
'ResolutionFailed' constraints not satisfiable: oadp-operator has a dependency without any candidates to satisfy it
```

That is most likely indication of an issue with your OperatorGroup. Please make sure that the OperatorGroup you're creating is correct. 

For eg, throughout this thread, `ppdm` and `ppmd` is used interchangeably. Typos like these can render the OG you're creating useless.  

PS: fyi that error message has been improved in I believe OCP 4.8 and above. The PR for that was https://github.com/operator-framework/operator-lifecycle-manager/pull/2258. But in OCP 4.6 unfortunately we have to deduce which dependency was not satisfied during the installation attempt. 

I'm guessing if you try to use the OperatorGroup that you used for 4.6 in a 4.8 cluster, you'll probably be able to figure out what's wrong faster.

**Comment by dymurray** [comment]
@yunjiang29 Can you please give us the output of:
```
oc get pod $(oc get pods -n openshift-marketplace | grep community-operators | awk '{print $1}') -n openshift-marketplace -o yaml | grep image

```

**Comment by Frank51** [comment]
This is from openshift 4.6.
```
# oc get pod $(oc get pods -n openshift-marketplace | grep community-operators | awk '{print $1}') -n openshift-marketplace -o yaml | grep image
            f:image: {}
            f:imagePullPolicy: {}
  - image: registry.redhat.io/redhat/community-operator-index:latest
    imagePullPolicy: Always
  imagePullSecrets:
    image: registry.redhat.io/redhat/community-operator-index:latest
    imageID: registry.redhat.io/redhat/community-operator-index@sha256:4a0c8b241c6b5d714a148117fd70a12a9a9df2ac77116f87dddb460154a5bed3
```
And this is from openshift 4.7 (where everything is ok)
```
# oc get pod $(oc get pods -n openshift-marketplace | grep community-operators | awk '{print $1}') -n openshift-marketplace -o yaml | grep image
            f:image: {}
            f:imagePullPolicy: {}
  - image: registry.redhat.io/redhat/community-operator-index:v4.7
    imagePullPolicy: Always
  imagePullSecrets:
    image: registry.redhat.io/redhat/community-operator-index:v4.7
    imageID: registry.redhat.io/redhat/community-operator-index@sha256:997ba076f230e5a222e46de62014b94e822e8e259043f9954d39a43d404a0365

```
