### ISSUE TITLE
Bug: backupImages: false in DPA cause error in getting route: configmaps oadp-registry-config not found

### ISSUE THREAD

**Issue by gorantornqvist** [openshift/oadp-operator#523]
### Describe bug

Hi,
I installed oadp-operator-0.5.3 and set backupImages: false in my DPA and this causes velero to hang when creating a new backup. The last error in the velero logs is:
```
time="2021-12-28T09:27:53Z" level=info msg="[common-backup] Error in getting route: configmaps \"oadp-registry-config\" not found. Assuming this is outside of OADP context." backup=openshift-adp/demo-customer-backup-xpfwc cmd=/plugins/velero-plugins logSource="/opt/app-root/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/backup.go:62" pluginName=velero-plugins
```
Any way to get past this?

Here is my DPA:
```
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: my-dpa
  namespace: openshift-adp
spec:
  configuration:
    velero:
      defaultPlugins:
      - openshift
      - aws
      - csi
      featureFlags:
      - EnableCSI
    restic:
      enable: true
  backupImages: false
  backupLocations:
    - name: demo-customer
      velero:
        provider: aws
        default: true
        credential:
          key: demo-customer
          name: cloud-credentials
        objectStorage:
          bucket: my-bucket
          caCert: LS0tLS1C...
        config:
          insecureSkipTLSVerify: "false"
          profile: default
          region: us-east-1
          s3ForcePathStyle: "true"
          s3Url: https://my-internal-s3
```

### What happened?

Velero hangs when backup is created

### OADP Version

0.5.x (Stable)

### OpenShift Version

4.9

### Velero pod logs

```shell
time="2021-12-28T09:27:53Z" level=info msg="[common-backup] Error in getting route: configmaps \"oadp-registry-config\" not found. Assuming this is outside of OADP context." backup=openshift-adp/demo-customer-backup-xpfwc cmd=/plugins/velero-plugins logSource="/opt/app-root/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/backup.go:62" pluginName=velero-plugins
```

### New issue

- [X] This issue is new

**Comment by kaovilai** [comment]
This is expected behavior. If your backup contains objects (such as [images](https://docs.openshift.com/container-platform/4.9/rest_api/image_apis/image-image-openshift-io-v1.html)) that requires oadp-registry to be deployed (ie. backing up images), you need to set `backupImages: true` to deploy said registry. If you insist on not backing up images, you need to exclude it from your backup ([velero docs](https://velero.io/docs/v1.7/resource-filtering/#--exclude-resources)); `velero backup create <backup-name> --exclude-resources image` should work for you although I have not tested this.

See [API reference](https://github.com/openshift/oadp-operator/blob/master/docs/API_ref.md) for more info

**Comment by gorantornqvist** [comment]
Thanks for your help.
I believe I have no other option than to disable the oadp-registry due to this bug: https://github.com/openshift/oadp-operator/issues/351 "x509: certificate signed by unknown authority in oadp-aws-registry pod"

I tried what you suggested:
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  namespace: openshift-adp
  generateName: demo-customer-backup-
spec:
  defaultVolumesToRestic: true
  storageLocation: sf-dpa-2
  includedNamespaces:
    - demo-customer
  excludedResources:
  - images.image.openshift.io
  - imagesignatures.image.openshift.io
  - imagestreamimages.image.openshift.io
  - imagestreamimports.image.openshift.io
  - imagestreammappings.image.openshift.io
  - imagestreams.image.openshift.io
  - imagestreamtags.image.openshift.io
  - imagetags.image.openshift.io
 ```
But I still get the same issue:
```
time="2021-12-29T14:44:37Z" level=info msg="Including resources: *" backup=openshift-adp/demo-customer-backup-bh7s8 logSource="pkg/backup/backup.go:225"
time="2021-12-29T14:44:37Z" level=info msg="Excluding resources: images.image.openshift.io, imagesignatures.image.openshift.io, imagestreamimages.image.openshift.io, imagestreamimports.image.openshift.io, imagestreammappings.image.openshift.io, imagestreams.image.openshift.io, imagestreamtags.image.openshift.io, imagetags.image.openshift.io" backup=openshift-adp/demo-customer-backup-bh7s8 logSource="pkg/backup/backup.go:226"
...
...
time="2021-12-29T14:45:04Z" level=info msg="[GetRegistryInfo] value from imagestream" backup=openshift-adp/demo-customer-backup-bh7s8 cmd=/plugins/velero-plugins logSource="/opt/app-root/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/shared.go:36" pluginName=velero-plugins
time="2021-12-29T14:45:04Z" level=info msg="[common-backup] Error in getting route: configmaps \"oadp-registry-config\" not found. Assuming this is outside of OADP context." backup=openshift-adp/demo-customer-backup-bh7s8 cmd=/plugins/velero-plugins logSource="/opt/app-root/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/common/backup.go:62" pluginName=velero-plugins
```
