### ISSUE TITLE
Problems airgapped install oadp-operator 0.4.2 in Openshift 4.7

### ISSUE THREAD

**Issue by stefffhem** [openshift/oadp-operator#569]
We have the Problem that we can't install OADP-Operator Airgapped over OperatorHUB. Operator was mirrored airgapped and the following Images are available:

imagecontentsourcepolicy:
```
spec:
  repositoryDigestMirrors:
  - mirrors:
    - registry.dev.net/olm-oadp-v47/konveyor-velero
    source: quay.io/konveyor/velero
  - mirrors:
    - registry.dev.net/olm-oadp-v47/konveyor-velero-restic-restore-helper
    source: quay.io/konveyor/velero-restic-restore-helper
  - mirrors:
    - registry.dev.net/olm-oadp-v47/konveyor-velero-plugin-for-gcp
    source: quay.io/konveyor/velero-plugin-for-gcp
  - mirrors:
    - registry.dev.net/olm-oadp-v47/konveyor-velero-plugin-for-csi
    source: quay.io/konveyor/velero-plugin-for-csi
  - mirrors:
    - registry.dev.net/olm-oadp-v47/konveyor-velero-plugin-for-microsoft-azure
    source: quay.io/konveyor/velero-plugin-for-microsoft-azure
  - mirrors:
    - registry.dev.net/olm-oadp-v47/konveyor-openshift-velero-plugin
    source: quay.io/konveyor/openshift-velero-plugin
  - mirrors:
    - registry.dev.net/olm-oadp-v47/konveyor-velero-plugin-for-aws
    source: quay.io/konveyor/velero-plugin-for-aws
  - mirrors:
    - registry.dev.net/olm-oadp-v47/konveyor-oadp-operator
    source: quay.io/konveyor/oadp-operator
  - mirrors:
    - registry.dev.net/olm-oadp-v47/konveyor-registry
    source: quay.io/konveyor/registry
```
catalogsource:
```
spec:
  displayName: olm-oadp-v47
  image: registry.dev.net/olm-oadp-v47/olm-oadp-v47-community-operator-index-pruned:v4.7.20220210
  publisher: ITZ v4.7.20220210
  sourceType: grpc
```

If we trigger a install there is a image missing during the operator install:
```
[root@vleosh3uxmda ~]# oc get pod -n openshift-marketplace | grep -i 922eeb749cba3b514ae88c3c0c90779d63f609efc3e5862a796bd3252edjs8b
922eeb749cba3b514ae88c3c0c90779d63f609efc3e5862a796bd3252edjs8b   0/1     Init:ImagePullBackOff   0          48m
```

describe to this pod there is a image missing which is not included in imagecontentsourcepolicy:
```
Events:
  Type     Reason          Age                    From               Message
  ----     ------          ----                   ----               -------
  Normal   Scheduled       50m                    default-scheduler  Successfully assigned openshift-marketplace/922eeb749cba3b514ae88c3c0c90779d63f609efc3e5862a796bd3252edjs8b to vlec2192ud2x.dev3.cloud
  Normal   AddedInterface  50m                    multus             Add eth0 [100.124.32.39/23]
  Normal   Pulled          50m                    kubelet            Container image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6ce678458f6b8bbc8c2bf38c2aa221fb7ad6f6207339735b6fac2aab076da7d6" already present on machine
  Normal   Created         50m                    kubelet            Created container util
  Normal   Started         50m                    kubelet            Started container util
  Normal   Pulling         49m (x4 over 50m)      kubelet            Pulling image "quay.io/openshift-community-operators/oadp-operator:v0.4.2"
  Warning  Failed          49m (x4 over 50m)      kubelet            Failed to pull image "quay.io/openshift-community-operators/oadp-operator:v0.4.2": rpc error: code = Unknown desc = error pinging docker registry quay.io: Get "https://quay.io/v2/": Service Unavailable
  Warning  Failed          49m (x4 over 50m)      kubelet            Error: ErrImagePull
  Warning  Failed          5m41s (x196 over 50m)  kubelet            Error: ImagePullBackOff
  Normal   BackOff         35s (x218 over 50m)    kubelet            Back-off pulling image "quay.io/openshift-community-operators/oadp-operator:v0.4.2"
```
