### ISSUE TITLE
Failed to backup PV data with restic in Minio environment

### ISSUE THREAD

**Issue by lebrisg** [openshift/oadp-operator#57]
I'm trying to test the OADP operator with a minio S3 server that I installed previously in an OCP 4.5 context.
The minio S3 server doesn't provide snapshots (as far as I know).
I created the secret cloud-credentials as specified in the documentation.

I tested the following configuration:

```apiVersion: konveyor.openshift.io/v1alpha1
kind: Velero
metadata:
  name: example-velero
  namespace: oadp-operator
spec:
  olm_managed: true
  use_upstream_images: true
  backup_storage_locations:
    - config:
        profile: default
        region: minio
        s3ForcePathStyle: "true"
        s3Url: "http://minio.example.com:9000"
      credentials_secret_ref:
        name: cloud-credentials
        namespace: oadp-operator
      name: default
      object_storage:
        bucket: velero
        prefix: velero
      provider: aws
  default_velero_plugins:
    - aws
    - csi
    - openshift
  enable_restic: true
  volume_snapshot_locations:
    - config:
        profile: default
        region: minio
      name: default
      provider: aws
```
I've got the following error message: "panic: invalid region provided: minio"

What could be the configuration to provide when using a Minio server (backup_storage_locations+volume_snapshot_locations)?

**Comment by jwmatthews** [comment]
I think minio defaults to use a region of "us-east-1" if you haven't explicitly changed this.
From your example you are using "region: minio"

**Comment by lebrisg** [comment]
I changed my initial configuration:
- using "us-east-1" instead of minio,
- specifying "enable_csi_plugin: true",
- removing "use_upstream_images: true" (otherwise, the velero pod doesn't get its image).

It seems to work.
```
apiVersion: konveyor.openshift.io/v1alpha1
kind: Velero
metadata:
  name: example-velero
  namespace: oadp-operator
spec:
  olm_managed: true
  enable_csi_plugin: true
  backup_storage_locations:
    - config:
        profile: default
        region: us-east-1
        insecure_skip_tls_verify: 'true'
        s3_force_path_style: 'true'
        s3_url: 'http://minio.example.com:9000'
      credentials_secret_ref:
        name: cloud-credentials
        namespace: oadp-operator
      name: default
      object_storage:
        bucket: velero
        prefix: velero
      provider: aws
  default_velero_plugins:
    - aws
    - csi
    - openshift
  enable_restic: true
  volume_snapshot_locations:
    - config:
        profile: default
        region: us-east-1
      name: default
      provider: aws
```
Then, I execute a test with a basic Wordpress application (PHP+MariaDB and its PV):
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  namespace: oadp-operator
  name: backup-wordpress
spec:
  includedNamespaces:
    - wordpress
  storageLocation: default
```
Finally, I delete the wordpress namespace and try to do a restore:
```
apiVersion: velero.io/v1
kind: Restore
metadata:
  namespace: oadp-operator
  name: restore-wordpress
spec:
  backupName: backup-wordpress
  restorePVs: true
```
I don't get any error and I can restore all the objects inside the namespace but the previous content of the PV is not there anymore.
Can you help me to understand what is wrong in my configuration?

**Comment by lebrisg** [comment]
The backup/restore via Restic doesn't work with pod annotation or 'defaultVolumesToRestic: true' in my configuration.

**Comment by jwmatthews** [comment]
It sounds like the backup/restore of the Kubernetes resources was successful, so the basic Velero workflow is OK.
The concern is that the contents of the PV data was not handled.

What kind of PVs are you using.  Velero has a few different ways to process PVs.

Some popular options would be:
 - NFS:  Would require Restic as of today
 - Cloud storage PVs (AWS EBS, Azure, Google, etc):  Potential for snapshots leveraging Velero plugins
 - Ceph (OCS):  Leverage CSI snapshots

I am guessing you may want to use Restic for the PV backup/restore.
In Velero 1.4.x you would need to add an annotation on the pod for Velero to process the PVs with Restic.
We recently updated OADP to deploy Velero 1.5.x, I believe in Velero 1.5 Restic will be leveraged automatically now for PVs if they don't match a configured snapshot rule.

Which version of OADP are you running now?  

cc @dymurray @shubham-pampattiwar @JaydipGabani @sseago @alaypatel07  (please comment if you see some other advice that would help to share)

**Comment by lebrisg** [comment]
I did a new battery of tests (OCP 4.7.1 in KVM/Fedora 33, OADP Operator 0.2.1, storage using NFS).

I launched a backup like below:

```
apiVersion: velero.io/v1
kind: Backup
metadata:
  namespace: oadp-operator
  name: backup-wordpress
spec:
  includedNamespaces:
    - wordpress
  storageLocation: default
  defaultVolumesToRestic: true
  ttl: 6h0m0s
```
I got the following error message several times (this might not be related to my Restic issue):

> level=error msg="Error backing up item" backup=oadp-operator/backup-wordpress error=**"pod volume backup failed: error getting volume path on host: expected one matching path, got 0"** error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:179" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:455" name=wordpress-git-2-build

Furthermore, Restic doesn't backup my PV when all the other Kubernetes objects are correctly backed up in my S3/Minio bucket.
When I restore, I get everything except my PV.

I can read the Velero logs with the command "velero backup logs backup-wordpress".
How can we do to read the Restic logs?
