### ISSUE TITLE
Error backing up ImageStreams

### ISSUE THREAD

**Issue by tsterk** [openshift/oadp-operator#640]
### Contact Details

tim.sterk@npo.nl

### Describe bug

We are currently experimenting with OADP and we are noticing that backups are partially failing:
```
hens-test-foo-01                            PartiallyFailed   1        1          2022-04-14 11:30:41 +0200 CEST   29d       dpa-hens-1         <none>
hens-test-foo-02                            PartiallyFailed   1        1          2022-04-14 11:06:16 +0200 CEST   29d       dpa-hens-1         <none>
```

### What happened?

It appears that there is a problem backing up the imagestreams, in the logs we notice that these are failing:
```
.svc:5000\", \"openshift.io/backup-server-version\":\"1.22\", \"openshift.io/generated-by\":\"OpenShiftWebConsole\", \"openshift.io/migration-registry\":\"oadp-dpa-hens-1-aws-registry-route-openshift-adp.apps.cluster.sandbox.npohosting.nl\"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:\"\", ManagedFields:[]v1.ManagedFieldsE
ntry{v1.ManagedFieldsEntry{Manager:\"Mozilla\", Operation:\"Update\", APIVersion:\"image.openshift.io/v1\", Time:(*v1.Time)(0xc000290a40), FieldsType:\"FieldsV1\", FieldsV1:(*v1.FieldsV1)(0xc000290a00)}}}, Spec:v1.ImageStreamSpec{LookupPolicy:v1.ImageLookupPolicy{Local:false}, DockerImageRepository:\"\", Tags:[]v1.TagReference(nil)}, Status:v1.ImageStreamStatu
s{DockerImageRepository:\"image-registry.openshift-image-registry.svc:5000/hens-test-foo/ruby-sample\", PublicDockerImageRepository:\"\", Tags:[]v1.NamedTagEventList{v1.NamedTagEventList{Tag:\"latest\", Items:[]v1.TagEvent{v1.TagEvent{Created:v1.Time{Time:time.Time{wall:0x0, ext:63785512925, loc:(*time.Location)(0x3032c00)}}, DockerImageReference:\"image-regis
try.openshift-image-registry.svc:5000/hens-test-foo/ruby-sample@sha256:b148f3e3c63fe30dc4e7e66bfd53369e02bd1e87cf320b8925cd1dbc7e14d45c\", Image:\"sha256:b148f3e3c63fe30dc4e7e66bfd53369e02bd1e87cf320b8925cd1dbc7e14d45c\", Generation:1}}, Conditions:[]v1.TagEventCondition(nil)}}}}" backup=openshift-adp/hens-test-foo-01 cmd=/plugins/velero-plugins logSource="/re
mote-source/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/imagestream/backup.go:38" pluginName=velero-plugins
time="2022-04-14T09:31:13Z" level=info msg="[is-backup] internal registry: \"image-registry.openshift-image-registry.svc:5000\"" backup=openshift-adp/hens-test-foo-01 cmd=/plugins/velero-plugins logSource="/remote-source/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/imagestream/backup.go:68" pluginName=velero-plugins
time="2022-04-14T09:31:13Z" level=info msg="[imagecopy] Copying tag: \"latest\"" backup=openshift-adp/hens-test-foo-01 cmd=/plugins/velero-plugins logSource="/remote-source/deps/gomod/pkg/mod/github.com/bombsimon/logrusr@v1.0.0/logrusr.go:108" pluginName=velero-plugins
time="2022-04-14T09:31:13Z" level=info msg="[imagecopy] copying from: docker://image-registry.openshift-image-registry.svc:5000/hens-test-foo/ruby-sample@sha256:b148f3e3c63fe30dc4e7e66bfd53369e02bd1e87cf320b8925cd1dbc7e14d45c" backup=openshift-adp/hens-test-foo-01 cmd=/plugins/velero-plugins logSource="/remote-source/deps/gomod/pkg/mod/github.com/bombsimon/log
rusr@v1.0.0/logrusr.go:108" pluginName=velero-plugins
time="2022-04-14T09:31:13Z" level=info msg="[imagecopy] copying to: docker://oadp-dpa-hens-1-aws-registry-route-openshift-adp.apps.cluster.sandbox.npohosting.nl/hens-test-foo/ruby-sample:latest" backup=openshift-adp/hens-test-foo-01 cmd=/plugins/velero-plugins logSource="/remote-source/deps/gomod/pkg/mod/github.com/bombsimon/logrusr@v1.0.0/logrusr.go:108" plug
inName=velero-plugins
time="2022-04-14T09:31:13Z" level=info msg="copying image: docker://image-registry.openshift-image-registry.svc:5000/hens-test-foo/ruby-sample@sha256:b148f3e3c63fe30dc4e7e66bfd53369e02bd1e87cf320b8925cd1dbc7e14d45c; will attempt up to 7 times..." backup=openshift-adp/hens-test-foo-01 cmd=/plugins/velero-plugins logSource="/remote-source/deps/gomod/pkg/mod/gith
ub.com/bombsimon/logrusr@v1.0.0/logrusr.go:108" pluginName=velero-plugins
time="2022-04-14T09:31:13Z" level=info msg="attempt #1 failed, waiting 5s and then retrying" backup=openshift-adp/hens-test-foo-01 cmd=/plugins/velero-plugins logSource="/remote-source/deps/gomod/pkg/mod/github.com/bombsimon/logrusr@v1.0.0/logrusr.go:108" pluginName=velero-plugins
time="2022-04-14T09:31:19Z" level=info msg="attempt #2 failed, waiting 10s and then retrying" backup=openshift-adp/hens-test-foo-01 cmd=/plugins/velero-plugins logSource="/remote-source/deps/gomod/pkg/mod/github.com/bombsimon/logrusr@v1.0.0/logrusr.go:108" pluginName=velero-plugins
time="2022-04-14T09:31:30Z" level=info msg="attempt #3 failed, waiting 15s and then retrying" backup=openshift-adp/hens-test-foo-01 cmd=/plugins/velero-plugins logSource="/remote-source/deps/gomod/pkg/mod/github.com/bombsimon/logrusr@v1.0.0/logrusr.go:108" pluginName=velero-plugins
time="2022-04-14T09:31:45Z" level=info msg="attempt #4 failed, waiting 20s and then retrying" backup=openshift-adp/hens-test-foo-01 cmd=/plugins/velero-plugins logSource="/remote-source/deps/gomod/pkg/mod/github.com/bombsimon/logrusr@v1.0.0/logrusr.go:108" pluginName=velero-plugins
time="2022-04-14T09:32:06Z" level=info msg="attempt #5 failed, waiting 25s and then retrying" backup=openshift-adp/hens-test-foo-01 cmd=/plugins/velero-plugins logSource="/remote-source/deps/gomod/pkg/mod/github.com/bombsimon/logrusr@v1.0.0/logrusr.go:108" pluginName=velero-plugins
time="2022-04-14T09:32:31Z" level=info msg="attempt #6 failed, waiting 30s and then retrying" backup=openshift-adp/hens-test-foo-01 cmd=/plugins/velero-plugins logSource="/remote-source/deps/gomod/pkg/mod/github.com/bombsimon/logrusr@v1.0.0/logrusr.go:108" pluginName=velero-plugins
time="2022-04-14T09:33:02Z" level=info msg="attempt #7 failed, waiting 35s and then retrying" backup=openshift-adp/hens-test-foo-01 cmd=/plugins/velero-plugins logSource="/remote-source/deps/gomod/pkg/mod/github.com/bombsimon/logrusr@v1.0.0/logrusr.go:108" pluginName=velero-plugins
time="2022-04-14T09:33:02Z" level=info msg="[imagecopy] Error copying image: writing blob: uploading layer chunked: received unexpected HTTP status: 500 Internal Server Error" backup=openshift-adp/hens-test-foo-01 cmd=/plugins/velero-plugins logSource="/remote-source/deps/gomod/pkg/mod/github.com/bombsimon/logrusr@v1.0.0/logrusr.go:108" pluginName=velero-plugins
```

I saw this in the aws registry pod logs:
```
074323ms http.response.status=500 http.response.written=123 vars.name=hens-test-foo/ruby-sample vars.uuid=8b398181-2d8c-481f-9309-1feea0ea52cb
time="2022-04-14T09:32:31.632889575Z" level=error msg="response completed with error" err.code=unknown err.detail="s3aws: AccessDenied: Access Denied\n\tstatus code: 403, request id: 3BRHB3S5Q8CF32QC, host id: 76s5V5sGSMWMII0qW6MGH4s2vh7A381mfJk1oHsUwfz5ZfMqGErPcxjfFXMSRaWNY19+KKWDVlg=" err.message="unknown error" go.version=go1.13.4 http.request.contenttype=application/octet-stream http.request.host=oadp-dpa-hens-1-aws-registry-route-openshift-adp.apps.cluster.sandbox.npohosting.nl http.request.id=fd8a43ba-e5d3-4421-a0aa-00ac5869f376 http.request.method=PATCH http.request.remoteaddr=35.181.132.188 http.request.uri="/v2/hens-test-foo/ruby-sample/blobs/uploads/f1e080a5-6470-4a4a-8d25-8df7ebbe3b9d?_state=o-lp8Jns9Sk8-KWIoksg8m6cwICnU9zmcBS6PRpPQSB7Ik5hbWUiOiJoZW5zLXRlc3QtZm9vL3J1Ynktc2FtcGxlIiwiVVVJRCI6ImYxZTA4MGE1LTY0NzAtNGE0YS04ZDI1LThkZjdlYmJlM2I5ZCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMi0wNC0xNFQwOTozMjozMS40NzQ0MzI1MTVaIn0%3D" http.request.useragent="containers/5.19.0 (github.com/containers/image)" http.response.contenttype=application/json http.response.duration=34.244263ms http.response.status=500 http.response.written=123 vars.name=hens-test-foo/ruby-sample vars.uuid=f1e080a5-6470-4a4a-8d25-8df7ebbe3b9d
```

Our DataProtectionApplication looks like this:
```
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: dpa-hens
  namespace: openshift-adp
spec:
  configuration:
    velero:
      defaultPlugins:
        - aws
        - csi
        - openshift
      featureFlags:
        - EnableCSI
      restic:
        enable: false
  backupLocations:
    - velero:
        provider: aws
        default: true
        credential:
          key: cloud
          name: cloud-credentials
        objectStorage:
          bucket: chp4-backups
          prefix: hens-backups
        config:
          region: eu-west-3
          profile: "default"
```

And the backup looks like this:
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: hens-test-foo-01
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  hooks: {}
  includedNamespaces:
  - hens-test-foo
  includeClusterResources: true
  storageLocation: dpa-hens-1
  ttl: 720h0m0s
```

### OADP Version

1.0.1 (Stable)

### OpenShift Version

4.9

### New issue

- [X] This issue is new
