### ISSUE TITLE
Pod restore plugin doesn't take into account `defaultVolumesToRestic` flag

### ISSUE THREAD

**Issue by GMerigo** [openshift/oadp-operator#74]
I'm trying the latest oadp version availlable in the Openshift Marketplace.
I'm able to backup kubernetes metadata (I tried to backup/restore a full namespace, including imagestreams) but I can't get restic restores to work, the test volume comes out empty, it seems like it's getting reprovisioned and never restored. **Note** that project and all other objects get correctly restored.

This happens both with OCS storageclasses and with gp2 as the backup/restore target volume.

----

The backup seems fine, I can see [...]/data/ populated in the S3 bucket and I can see the podvolumebackup if I issue the `oc get podvolumebackups.velero.io  -n oadp-operator` command.

The backup has the `  defaultVolumesToRestic: true` option so the volume backups should initiate even without annotating pods.

The Restore object is configured this way:

```
apiVersion: velero.io/v1
kind: Restore
metadata:
  namespace: oadp-operator
  name: restore-test-restic-all-4
spec:
  backupName: test-restic-all
  includedNamespaces:
    - test-restic
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  restorePVs: true
```

Note that in the logs there are no errors related to the pv or pvc restores (there's an error in the imagestream but in this case I don't care as the test environment uses a standard openshift image).

Maybe I'm missing some critical parameter in the restore request?

----

These are the versions involved:

Openshift 4.5.18 on AWS
Openshift Container Storage: ocs-operator.v4.5.0
oadp: oadp-operator.v0.2.0
velero: (default image) Version: v1.5.2-konveyor
Storage and Snapshot locations: AWS S3

Note that I can't currently update to a OCS version with snapshot support, so I'm currently unable to use CSI snapshots, so it would be nice to have restic backups and restores working, at least for small volumes.
