### ISSUE TITLE
Mount SSE-C Encryption file for the AWS plugin

### ISSUE THREAD

**Issue by WafaAmr** [openshift/oadp-operator#837]
**Is your feature request related to a problem? Please describe.**
The [AWS plugin](https://github.com/vmware-tanzu/velero-plugin-for-aws) supports Server-Side Encryption with Customer-Managed Keys.

For example:
```
apiVersion: velero.io/v1
kind: BackupStorageLocation
...
spec:
  provider: velero.io/aws
  config:
    ...
    serverSideEncryption: AES256
    # Specify the file that contains the SSE-C customer key to enable customer key encryption of the backups
    # stored in S3. The referenced file should contain a 32-byte string.
    customerKeyEncryptionFile: "/credentials/customer-key"
```

 As stated in the [AWS:BSL documentation](https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/0384addf5eee27b81dc69d4450e2359749ce1cf5/backupstoragelocation.md?plain=1#L74), I can define a path to the encryption file. The question now, Where should I specify the name of the Secret object `customer-key` to be mounted inside the velero-pod? 

`"Error getting backup store for this location" backupLocation=velero-sample-1 controller=backup-sync error="rpc error: code = Unknown desc = provided customerKeyEncryptionFile does not exist: /credentials/customer-key: stat /credentials/customer-key: no such file or directory" `

**Describe the solution you'd like**
Provide a way to specify the secret `customer-key` as followed in backupLocation credential.
**Additional context**
OpenShift version : 4.9.48
OADP-Operator version : 1.1.0
