### ISSUE TITLE
support self-built minio?

### ISSUE THREAD

**Issue by 51qzpw** [openshift/oadp-operator#875]
### Contact Details

51qzpw@gmail.com

### Describe bug

s3Url is not a valid AWS config value

### What happened?

I would like to use it in my self-built k8s cluster, Minio is also my own built
my cr yaml:
```yaml
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: velero
  namespace: openshift-adp
spec:
  configuration:
    velero:
      podConfig:
        resourceAllocations:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
      defaultPlugins:
#        - openshift
        - aws
        - kubevirt
        - csi
      featureFlags:
        - EnableCSI
    restic:
      enable: true

  backupLocations:
    - velero:
        provider: aws
        default: true
        objectStorage:
          bucket: "oadp"
          prefix: "velero"
        config:
          region: us-east-1
          s3Url: http://10.0.34.12:9000
#          s3ForcePathStyle: "true"
        credential:
          name: cloud-credentials
          key: cloud
  snapshotLocations:
    - velero:
        provider: aws
        config:
          region: minio
          s3Url: http://10.0.34.12:9000
#          s3ForcePathStyle: "true"
```

### OADP Version

1.0.3 (Stable)

### OpenShift Version

None

### Operator pod logs

```shell
1.6708329056470814e+09  ERROR   controller.dataprotectionapplication    Reconciler error        {"reconciler group": "oadp.openshift.io", "reconciler kind": "DataProtectionApplication", "name": "velero", "namespace": "openshift-adp", "error": "s3Url is not a valid AWS config value"}
```

### New issue

- [X] This issue is new
